### ISSUE TITLE
安装失效

### ISSUE THREAD

**Issue by ShiinaOrez** [Ice-Cirno/HoshinoBot#101]
按照步骤在Linux Ubuntu阿里云机器上进行了搭建，各步骤检查了很多遍。但是仍然没有效果。

这可能不叫一个ISSUE，但是希望可以得到帮助。

详细信息：
1. 使用CoolQ Air：xiaoi
2. docker ip桥为：172.17.0.1
3. 改动了config.py 中的SUPERUSERS，NICKNAME 和 HOST
4. CoolQ上正常登陆账号，QQ上私聊BOT，在群艾特BOT，发送指令均无响应

**Comment by ShiinaOrez** [comment]
可能和ISSUE#100类似，应该是反向Websocket失效了

**Comment by Ice-Cirno** [comment]
请查看Hoshino的日志，检查Hoshino是否与酷Q正常连通。
