### ISSUE TITLE
bot发送图片失败

### ISSUE THREAD

**Issue by H-K-Y** [Ice-Cirno/HoshinoBot#104]
在使用官漫 来一井 jjc查询时都不能发送图片，酷Q后台报错
文件名不合法，无法发送！(base64://iVBORw0KGgoAAAANSUhEUgAABCgAAAZ7CAIAAABajxPbAAEAAElEQVR4nOz9Z7Rk2XkdCO7vmOvCPu/SZ1ZmuSwHoBxQKIIwhBPRMpRItrxmidOzZLs106PWmh+z1EZa6p5erV5rRiOxQYkSKUEjLoIECdCJ8KZQqEJVIctkpc98+bwJf90555sfNyJeZFa+YmWxCFQVYq9cL+PdF3HjXBPvnX2+vb9NAKSUlUql1WpNTk4KITY2Nqanp3d3dzHGGGOMMcYYY4wxxjsfQgjnnHOOmQEQkRCi2PgjGY9nwWCH/rsLCCmkEMJaC6AYJIMZ/QcQcjhQpr2vDgABN30FpLm98Vi2IAIAor0HAPY5P56jW4+H+Zbj0dnwWPrD5uKnUoLQ/4e9l1DqmEBEwN5X4QDnFEMCClCABCRAwHVF/dfSjW9t7Q1vycXPKQIX29DfDEdgAgSY4Iof8cjxWv+W56G4Uq8FeYiiqNFoAPA8L8syAFEUUa1WY+Y4jvM8Hz5bSllc+DHGGGOMMcYYY4wxxnhr4d3m8/ORx/2pLo1sunGWDwJuk3jcsLc38vSR+fYbGY9ngJGJ/h7xAG5JPG49fu4zDYE+9ygeE7D5OrvikXcdfBsNnuKGxGP49bV7AKRVr3M2Xgs7cgCVSiXLsjRNp6amVJqmzrkh6yAiImJm3781sxljjDHGGGOMMcYY450Fz/PcAADEAMVS9A8fJaFHxzOswOy3gp7w3oI40w0P3I0bHQGAJ29vPFLe+gX7jYftXiVkdDxCiFuPJ7bFYyIqSgpMGD7oVxtGoOTePpm54DkCUEJKhnQQDMGQDGIQw/fc8GzccofEEAw4LvYT2cHzi3LN4FUQNDq24YGo5NbEQwhxy+2d1FSr1aKw4XleUc9otVp7g5qenk6SpNPplMvlTqdzy72MMcYYY4wxxhhjjDHGHxNvQcWjwH6VilvzhX1xmzwFowKsNzIen/ee5v7IosdNb3DTOzFoUOgQgxdlo0+5ldbrpp2U3N53ty563Pha5W5NMPaDgatWq91u11obBIExxhgDQBGRlNIYI4Qo+Mbi4uKrr76q1O2VVMYYY4wxxhhjjDHGeHvC8zxmttYOPR5SSiL6UVU8Iuk556y11lnXd2pQ/x9RUQAZfiWiVp78iY6npgJmZubCBlN85f3pS6ZuzTD2q5DAWgEiEEBSCiIiKRyQWzOse4xyD6F1MR5Yh+FXZkjZZwAMBoZloND1X+kGhpNin1IrB1h2DgznBsYZ1g54jfRrUPQAE2gwSCJiImrf2oKx7/EqVavV0jS11iZJorUGoLVWYRhaa40xRREkDMN/+A//4draWvGMMcYYY4wxxhhjjDHe6Riay2+SWv2ozOUBC+dcsRBezPJv4hujIKKuy2/aw6jL4rWr8fY2PRs16IJvjKIY1S2fb0o312yK8RRE7rXjodT0D1BKkgJSCCEgKOebJVIFpKcB9AdkLKyDY7pxlj8qhZpxe+MZaqgYYCUM2LLL2eVwubMWzMwHUt575lCdBTgwCyIpIARJIYQouIfs3fo+2Y+4JoKCIPjWt771+7//+3EcSynzPCci1ev1CllbuVze3t4+efLkX/2rf/WWuxhjjDHGGGOMMcYY4x2K4cQaA+Kx36z6hwELMMMYa8ywDgNAKVUQD0iJEd8FS2BU+zM6A+cbtxQPble4Mzp/thbWwjkwY59TxNXgluPJk6TvxxhsKb7l3BS8ClJASigJoj5BoRtbXQEA0oGSSvT7VjGMg3NFneC1FpGqCW44IUOtVLELYsM2ZZvB5XCWeSFm4DWiLIJjhiBIIdQN538/JsfJrStRxvN7vZ5S6vnnn798+XLBT4wxCoBSylpbqVQAFF10i6feckdjjDHGGGOMMcYYY7yzUBQWXlvx+FHN92RmrbV5nptbEQ8pZTE2IYSUEkSZG/SO4v5XMXgs+DWsA8hus5DjZQTmgm+wMYUM7HUqHhyKW46n2+6IwvCNwdgAADY3/UqOkqSkkFIIwUoUgise0UcVcNqTAIOds5xbyi1yKxznWYZBNcMKWOozEPCgyjI8FX3hlgMck0vJJrAxbAZnmW2PMaLLGnIYCwaRUBJSSK2EECQlESlza0lVt9O+5XZd10mS7O7urqysFO4OAOVyWQEovj9z5sxQXhUEwX4u9THGGGOMMcYYY4wx3lnQWud5nqbp0OPheZ7W+o0XPay1o5qoUbyJ8bg8KRQ3RXbHcOdaaymlUkpqDSmHBQciS0SKBAAqmko5x9aRccDAHF2AAcAr9SsAw+P9IwbULzo45DlxYYdA4YopCIOUUkpJRR2GyGqPwXBOCCFANjdxt5v04kDqvuebB/UMBgCpVMGjjHN5llvkOvC1UoCQkgAwERMgCACB1rJOzSsLEKyTlpUfQQHtrqpOAwNSUVjLsyRJU5AHa5EbJCl2d9HrYWoK87NFw10ysc5yBEr7QSvp7XSaQpQwKHUUlRYiOCAIgk7c63WSsBQF1SqI2JpWq1WGGHpghjq04nq99n4gomYcz83NRVGUpimASqXSbrfjOB6XNcYYY4wxxhhjjDHe5RjOnouJeFFSeJ3p+GsX+4sl6dFIO7yRCf0+GO2cW0xVb2I1N49GgAA3sE/0XdfWZWk62lV2j37UArxx1oHBHFwQpACUJAgnCxfK8NRRIQATAkRDcdRwnb7oV0u4ocutGJQ+chpsGS3UAJCq2EVhPB+iKAZIwOVWQcMABiAfjbg4fhBDEJSAloEqYauHS5fXLl7cWd9sNZpxHEflUm12+s5H34fZScxOeNXQc+lu3HPGBJ5P+d5RC+5XWgQBjgVDEFHRe1cQW0cMYlu40gUz2FHf6s6CHRh7/pziOBhSe6NnvrgQ1t5mGsgYY4wxxhhjjDHGGO9EKKWYueAPRVXhdZ5c9DsdTbcYOr/fqtEQs3SuMLhLKYfEo9CAFfP70VfsxWUwE7N1jqzL4kQyDEO6/qS/mNY7U

shell没有错误显示
[2020-06-15 12:24:24,490 gacha] INFO: Message 185 is handled as command by gacha_300.
[2020-06-15 12:24:24,490 nonebot] INFO: Message 185 is handled as a command

但是使用shebot就能发送图片
我使用的Ubuntu 19.10 x64 在docker中部署的

**Comment by Ice-Cirno** [comment]
出错原因可能是酷Q那边无法将b64转码为图片。
hoshino v2 将支持file协议，可以解决这个问题，敬请期待！

**Comment by H-K-Y** [comment]
> hoshino
> v2将支持文件协议，可以解决这个问题，敬请期待！错误的原因可能是酷Q那边无法将b64转码为图片。

我试了一下，把来一井或竞技场图片的base64码先保存到硬盘，然后再吧路径传给酷Q就能正常发图了
