### ISSUE TITLE
命令前缀没有生效

### ISSUE THREAD

**Issue by Mizuho486** [Ice-Cirno/HoshinoBot#117]
虽然在设置里填写了前缀的符号，但实际似乎只有私聊 在？的时候才会起效。。原因不明

**Comment by Ice-Cirno** [comment]
命令前缀是nonebot的特性，Hoshino并没有用到。
当前版本使用的on_prefix等触发器不会识别命令前缀。
命令前缀仅对on_command装饰器起作用。

**Comment by Mizuho486** [comment]
> 命令前缀是nonebot的特性，Hoshino并没有用到。
> 当前版本使用的on_prefix等触发器不会识别命令前缀。
> 命令前缀仅对on_command装饰器起作用。

原来如此。。这个功能对我来说还是挺要紧的，不过也没办法，谢谢啦

**Comment by Ice-Cirno** [comment]
对于on_prefix和on_fullmatch装饰器，要实现命令前缀并不困难，你通过可以修改hoshino/trigger.py的add方法来实现。
对于on_suffix和on_keyword似乎没有较好的方法添加。对于on_rex可以通过直接修改正则表达式来实现。
