### ISSUE TITLE
关于工会战boss状态重新设置的指令

### ISSUE THREAD

**Issue by GrandArashi** [Ice-Cirno/HoshinoBot#125]
我貌似没有在帮助中看到，可以更改吗

**Comment by Ice-Cirno** [comment]
cmdv2版无该功能，每月20日自动切换，详细请看指令一览表底部的FAQ。
clanbattlev3将会添加该功能。

**Comment by GrandArashi** [comment]
> 
> 
> cmdv2版无该功能，每月20日自动切换，详细请看指令一览表底部的FAQ。
> clanbattlev3将会添加该功能。

好的
