### ISSUE TITLE
bot推特转发时图片发送失败

### ISSUE THREAD

**Issue by Mercury-Lamp** [Ice-Cirno/HoshinoBot#126]
在bot转发推特消息时，仅有文字发送出来而没有图片，酷q日志报错：“文件名不合法，无法发送！(http://pbs.twimg.com/media/EctbLXUUMAA8s7K.jpg)”

而windows powershell无错误显示：
[2020-07-12 15:43:56,622 twitter-poller] INFO: 成功获取@ywwuyi的新推文1条
INFO:twitter-poller:成功获取@ywwuyi的新推文1条
[2020-07-12 15:44:24,171 kc-twitter] INFO: 群1087439520 投递kc-twitter成功 共1条消息
INFO:kc-twitter:群1087439520 投递kc-twitter成功 共1条消息

是在windows下部署的，发送图片协议选择的是file

**Comment by Ice-Cirno** [comment]
错误原因目测是酷Q所在机器无法访问推特的图片服务器。
解决办法：1. 给酷Q所在机器挂全局梯子（大陆的绝大多数VPS提供商不允许这样做）；或2. （假定Hoshino所在服务器可以访问正常访问推特）修改推特模块，将图片下载后转为base64发送。

**Comment by Mercury-Lamp** [comment]
感谢回复
酷q所在机器挂的已经是全局代理，应该是第二种情况，我去试着改一下

**Comment by Ice-Cirno** [comment]
hoshino给酷Q发送的仅是图片的url，如果全局代理也没用的话，那应该是cqhttp插件的问题了，我不清楚cqhttp插件是否有走代理的配置选项，你可能需要查阅相关文档：https://cqhttp.cc/
解决方法2应当可以帮到你。
之后如果有时间了我再改进吧，写twitter转发插件时并没有考虑过境内部署的问题。（或者提个pr？
