### ISSUE TITLE
啊这，是否支持mirai 一键包

### ISSUE THREAD

**Issue by samondlee** [Ice-Cirno/HoshinoBot#133]
啊这，是否支持mirai 一键包
https://github.com/LXY1226/MiraiOK

**Comment by xhl6666** [comment]
HoshinoBot是基于[NoneBot](https://github.com/nonebot/nonebot)框架开发的，而NoneBot框架并不支持Mirai。

**Comment by Rimliya** [comment]
> HoshinoBot是基于[NoneBot](https://github.com/nonebot/nonebot)框架开发的，而NoneBot框架并不支持Mirai。

mirai有个Python的版本，那个也不支持吗

**Comment by xhl6666** [comment]
> > HoshinoBot是基于[NoneBot](https://github.com/nonebot/nonebot)框架开发的，而NoneBot框架并不支持Mirai。
> 
> mirai有个Python的版本，那个也不支持吗

可以部署HoshinoV1

**Comment by Ice-Cirno** [comment]
Hoshino仅依赖cqhttp，而与具体的qq客户端无关。理论上只要qq端实现了cqhttp的接口就能使用。
