### ISSUE TITLE
推特转发出现超时卡顿

### ISSUE THREAD

**Issue by Watanabe-Asa** [Ice-Cirno/HoshinoBot#140]
Execution of job "twitter_poller (trigger: interval[0:00:16], next run at: 2020-08-13 00:08:14 CST)" skipped: maximum number of running instances reached (1)
可能是任务执行的时间太长，定时程序执行到这里后就一直等待返回，没有返回导致卡顿。
也许和框架有问题。姑且先开个issue。后续测试后再补充）

**Comment by Ice-Cirno** [comment]
请确认你搭建bot的服务器可以正常访问推特
尝试`ping twitter.com`

**Comment by Watanabe-Asa** [comment]
64 bytes from 104.244.42.1 (104.244.42.1): icmp_seq=132 ttl=58 time=0.346 ms
64 bytes from 104.244.42.1 (104.244.42.1): icmp_seq=133 ttl=58 time=0.349 ms
^C
--- twitter.com ping statistics ---
133 packets transmitted, 133 received, 0% packet loss, time 132056ms
rtt min/avg/max/mdev = 0.298/0.356/0.414/0.026 ms
服务器可以正常访问twitter.com

**Comment by Watanabe-Asa** [comment]
已测试是go-cqhttp旧版的问题。更新至go-cqhttp-v0.9.18可解决。
