### ISSUE TITLE
需要res资源包，但群已满

### ISSUE THREAD

**Issue by Cathgao** [Ice-Cirno/HoshinoBot#150]
![image](https://user-images.githubusercontent.com/21031564/92309138-7e0bda80-efd5-11ea-8ef0-1dae98a53c64.png)

**Comment by Mateoust** [comment]
你可以从这个链接下载：https://wws.lanzous.com/iBrAcdjc8li

**Comment by Cathgao** [comment]
> 你可以从这个链接下载：https://wws.lanzous.com/iBrAcdjc8li

感谢提供
