### ISSUE TITLE
arm下armbian安装python.385红字报错h11、aiocqhttp

### ISSUE THREAD

**Issue by samondlee** [Ice-Cirno/HoshinoBot#151]
ERROR: httpcore 0.10.2 has requirement h11<0.10,>=0.8, but you'll have h11 0.10.0 which is incompatible.
ERROR: nonebot 1.6.0 has requirement aiocqhttp<1.3,>=1.2, but you'll have aiocqhttp 1.3.0 which is incompatible.

啊这 

有无dalao知道怎么处理emmm

**Comment by corvo007** [comment]
新issue?你去百度就没了

**Comment by samondlee** [comment]
> 新issue?你去百度就没了

都是最新的了

Requirement already up-to-date: h11 in /usr/local/lib/python3.8/site-packages (0.10.0)

**Comment by cloudpursuer** [comment]
问题解决了吗？我想知道如何处理
