### ISSUE TITLE
jjc

### ISSUE THREAD

**Issue by RicardoCZ** [Ice-Cirno/HoshinoBot#153]
![0S79`952@@T8H$DRC6H8R47](https://user-images.githubusercontent.com/65592453/96368982-c21ffc80-1189-11eb-8f1e-17d2c474704b.png)
![)(G($9ZW9BCEIG{ GKURXFQ](https://user-images.githubusercontent.com/65592453/96368984-c77d4700-1189-11eb-9950-8ee94d6955b9.png)
jjc查询出现这个问题咋解决啊

**Comment by maxesisn** [comment]
你的图片资源内少了四张点赞/点踩图标，建议自己补全

**Comment by RicardoCZ** [comment]
点赞点踩有图标吗，我启用hoshono1.0的版本的话jjc查询好的但是最新的2.0就会出现我图片分享的情况



---Original---
