### ISSUE TITLE
使用go部署hoshino遇到如图情况

### ISSUE THREAD

**Issue by RicardoCZ** [Ice-Cirno/HoshinoBot#154]
![DG1P(ZV@UQYR0K_ AT3$QLR](https://user-images.githubusercontent.com/65592453/96492346-17393c80-1276-11eb-9e08-51ddc3468f5b.png)
请问使用go部署遇到这种情况应该修改哪个文件

**Comment by Ice-Cirno** [comment]
请尝试同时启动go-cqhttp与HoshinoBot
