### ISSUE TITLE
会战周期问题修正

### ISSUE THREAD

**Issue by zzpong** [Ice-Cirno/HoshinoBot#156]
由于国服特色的28天会战循环，2020年10月国服会战开始后，数据库无法及时更新（报刀依然显示上月会战数据）。但我还在用着v1版本的代码，无法直接pr，所以就把功能函数放这儿了，算是抛砖引玉吧。

1. 函数将会战三个服务器分离开，并给每个服务器增加“会战起始时间”以及“会战周期”参数，保证稳定长久运行；
2. 函数提供“判断本日是否会战”以及“判断本日最近会战时间（与hoshino原函数一样，向前取整）”功能。

* 国服会战28天循环会导致一月两次会战的情况，使数据库命名冲突，建议在数据库table名中增加日期信息。

以下是v1版本修正位置：
bm.get_yyyymmdd(now, server) 增加服务器输入变量，cmdv2调用为 bm.get_yyyymmdd(now, clan['server'])；
增加功能可以按喜好添加，简单替换也行，注意格式对应就好了。

* 如果bot在台服，且想在数据库table名中增加日期信息的话，请等到会战结束后更新。

[clan_battle_check.zip](https://github.com/Ice-Cirno/HoshinoBot/files/5438838/clan_battle_check.zip)

**Comment by Ice-Cirno** [comment]
2019年（笑

**Comment by zzpong** [comment]
时间bug已修正 😂
来回调也行，年轻人的第一次删库 😆
