### ISSUE TITLE
How to download Cool Q Air?

### ISSUE THREAD

**Issue by Natsume150** [Ice-Cirno/HoshinoBot#158]
I can't download it, can't access the download sites, what should I do? I used VPN but still can't access.

**Comment by noahzark** [comment]
Cool Q is a deprecated project which abandoned by original author several months ago, as mentioned in another issue, you could register at leaset 2 Tencent QQ accounts, and use [go-cqhttp](https://github.com/Mrs4s/go-cqhttp) (strongly recommendly) or [mirai](https://github.com/yyuueexxiinngg/cqhttp-mirai) (harder to deploy)
