### ISSUE TITLE
出刀记录异常

### ISSUE THREAD

**Issue by SaarChaffee** [Ice-Cirno/HoshinoBot#163]
今天有个人报错刀直接撤回了消息，导致我们在打B5的时候，boss记录突然变成了B1，然后出刀记录在B2之后就没了
![image](https://user-images.githubusercontent.com/53519746/99867173-0cb1f000-2bf2-11eb-9720-61f471875241.png)
![image](https://user-images.githubusercontent.com/53519746/99867182-23584700-2bf2-11eb-944d-a0ed55a064d4.png)
![image](https://user-images.githubusercontent.com/53519746/99867190-2bb08200-2bf2-11eb-8826-56347b40d068.png)
![image](https://user-images.githubusercontent.com/53519746/99867205-6a463c80-2bf2-11eb-9909-ccbd98c7f2e4.png)

**Comment by Ice-Cirno** [comment]
删掉E469、E470及其之后的记录再尝试。
10周目5王 后 为 11周目1王，不存在问题。
出刀记录是显示问题，当前发送长消息容易被tx吞。
=======
使用过程中的此类问题请先尝试与维护组私聊

**Comment by SaarChaffee** [comment]
不不，这两条记录是连着的，B5刚报完刀，然后就直接跳到B1了

**Comment by Ice-Cirno** [comment]
E469伤害报多了直接把老五给斩了，那可不就老一了嘛...

**Comment by SaarChaffee** [comment]
哦对哦，谢谢我去试一下

**Comment by SaarChaffee** [comment]
诶这样的话我建议加一个伤害溢出的判断来防止这种问题xd
