### ISSUE TITLE
卡池概率错误

### ISSUE THREAD

**Issue by yuban01652** [Ice-Cirno/HoshinoBot#164]
fes池的克里斯蒂娜up概率是0.7%，不是config提供的1.4%

**Comment by Cappuccilo** [comment]
卡池的config是要维护组自己修改的，包括up角色和概率。如果有使用其他自动更新卡池的插件，请去联系插件作者，与hoshino无关

**Comment by yuban01652** [comment]
> 卡池的config是要维护组自己修改的，包括up角色和概率。如果有使用其他自动更新卡池的插件，请去联系插件作者，与hoshino无关

？大佬你是不是搞错了什么，我说的是4天前Ice-Cirno大佬更新了hoshino的config，就在这个git的config里啊

**Comment by Ice-Cirno** [comment]
模拟抽卡图一乐，提供概率不代表游戏内出率。
抽卡数据更新较频繁，本repo内数据仅供参考，不保证及时更新也不保证与实际游戏一致。
请根据需要自行调整。
