### ISSUE TITLE
请教机器人无反应原因

### ISSUE THREAD

**Issue by huang12zheng** [Ice-Cirno/HoshinoBot#166]
* 前提
1.  go-cqhttp 跑起来了
2.  发`在?` , HoshinoBot会有回应

* 问题
但我发 .r  或  沙雕机器人 都没有反应
 
* 图
![截屏2020-12-13 上午7 25 16 (2)](https://user-images.githubusercontent.com/28038074/101999324-bc244300-3d16-11eb-8fe3-86c4a859eb9a.png)

**Comment by syozzz** [comment]
.r 或者沙雕机器人是群消息的指令 你是私发的
