### ISSUE TITLE
请问下群成员抽卡被禁言 这是彩蛋么 还是 bug

### ISSUE THREAD

**Issue by syozzz** [Ice-Cirno/HoshinoBot#167]
环境：centos7 + go-cqhttp 0.9.34 + HoshinoBot + yobot 
插件：安装了 pcrbot.com 推荐的一些娱乐插件
问题：普通群成员十连或者井有被禁言若干分钟的现象 管理员没有
请问各位有遇到或者有思路吗，打扰了

**Comment by laipz8200** [comment]
防刷屏用

**Comment by laipz8200** [comment]
> 环境：centos7 + go-cqhttp 0.9.34 + HoshinoBot + yobot
> 插件：安装了 pcrbot.com 推荐的一些娱乐插件
> 问题：普通群成员十连或者井有被禁言若干分钟的现象 管理员没有
> 请问各位有遇到或者有思路吗，打扰了

是防止刷屏用

**Comment by syozzz** [comment]
> > 环境：centos7 + go-cqhttp 0.9.34 + HoshinoBot + yobot
> > 插件：安装了 pcrbot.com 推荐的一些娱乐插件
> > 问题：普通群成员十连或者井有被禁言若干分钟的现象 管理员没有
> > 请问各位有遇到或者有思路吗，打扰了
> 
> 是防止刷屏用

那可以在设置里取消这个限制吗

**Comment by Cappuccilo** [comment]
可以，把bot管理员下了

**Comment by syozzz** [comment]
> 可以，把bot管理员下了

好的，谢谢
