### ISSUE TITLE
jjc解法查询的问题

### ISSUE THREAD

**Issue by reF1nd** [Ice-Cirno/HoshinoBot#172]
在查询国服JJC解法的时候，如果阵容内包含“环奈”或者“环奈(振袖)”，就会报查询出错code110。`_pcr_data.py`里已添加春环，ID为1702(环奈为1701)。之前有环奈还能正常查询，现在有环奈都会报错，估计是查询接口那边的变化吧？

**Comment by reF1nd** [comment]
更新：现在不会报110错误了，现在是查询阵容里含有环奈或者春环会直接提示查询不到解法，而实际去pcrdfans.com查询是有相关结果的

**Comment by Ice-Cirno** [comment]
这是数据库那边的限制，不属于hoshino本身的问题。
