### ISSUE TITLE
请问下运行run.py出现这个报错是怎么回事？

### ISSUE THREAD

**Issue by Joan-Of-Arc** [Ice-Cirno/HoshinoBot#176]
环境：win10，go-cqhttp-v0.9.39，py3.6, Hoshinobot
插件：只有自带的一些
问题：配置好了以后报这个错误，请问各位有遇到或者有思路吗，谢谢各位
![image](https://user-images.githubusercontent.com/37995966/106522285-7451b900-651a-11eb-9960-24dba158ce8e.png)

**Comment by Ice-Cirno** [comment]
请检查nonebot版本>=1.6.0, <2.0.0
