### ISSUE TITLE
想问下禁私聊的原因

### ISSUE THREAD

**Issue by klarkxy** [Ice-Cirno/HoshinoBot#177]
看到代码里面有判断，如果是私聊消息直接False
想知道这个的原因。
是鹅厂那边的坑还是机器人的坑。。

**Comment by Ice-Cirno** [comment]
1. 主要功能开发时未考虑过私聊场景，贸然开放私聊会有bug（如尝试获取group_id会抛出异常）
2. `service`层的一个重要特性是分群权限管理；私聊需要根据用户uid来进行管理，需要重新设计。
3. 登录小号会看到一堆私聊，很烦（bushi

你可以使用nonebot原生的on_command来开发私聊功能。
