### ISSUE TITLE
不同 Service 多个 Trigger 命中时只触发了一个

### ISSUE THREAD

**Issue by clacknya** [Ice-Cirno/HoshinoBot#178]
在 config 中加入了 `anti-holo` 模块后，即使是禁用状态，当一条消息被 `on_keyword` 命中后，其它 Service 的 Trigger ，如 `on_rex` 就被忽略了。

**Comment by Ice-Cirno** [comment]
This is a feature.

**Comment by clacknya** [comment]
为什么是 feature ？该模块是 **禁用** 状态的

**Comment by Ice-Cirno** [comment]
这是出于性能上的考虑而做出的妥协。

触发器的优先级为on_prefix/on_fullmatch > on_suffix > on_keyword > on_rex >> on_commad等nonebot原生触发器
对于每条消息，最多只会触发1个function。一方面避免滥用（试想有用户将所有的keyword拼接成一条消息，同时满足某个on_prefix和多个on_rex），另一方面可以减少匹配时的复杂度。
而 启用状态判定 是在 匹配触发器 之后：我们必须先确定触发了哪个function，才能根据function的属性来判断启用状态。

如果希望在模块禁用时不影响其他功能的触发，可能的解决方法有：
1. 首先判断启用状态，仅对启用的功能构建触发链，再进行匹配。nonebot 1在某个版本添加了插件管理，其解决方法就是如此。但注意，对于 **每条消息** 我们都要重新构建触发链，由于我们自动添加了繁体支持，触发词会比你想象的要多，对**每条消息**都要**重新构建**触发链是相当大的性能开销！
2. 匹配出所有可能的function（对于on_prefix，除了最长前缀，还可以匹配任意最长前缀的子前缀），按顺序逐个判断是否启用。这种方式的性能开销略小些，但会增加代码的复杂度。

我推荐的做法是：
- 常用、明确的指令使用on_prefix/on_fullmatch/on_suffix触发器，它们具有高效、无二义性的特点。
- 不常用、无关紧要的指令使用on_keyword/on_rex触发器，这类触发器的匹配开销较大，优先级较低。（事实上，Hoshino自带的功能已经很少再使用这类触发器了）

虽然不能完全解决问题，但以下方法可能会帮到你：
- 尝试将on_rex更改为on_prefix触发
- 或，注释掉anti_holo.py第106行 或 删除本功能
- 或，将hoshino.trigger.chain中rex提至keyword之前

*计划中的开发文档将会详细说明trigger的触发方式及使用建议*

**Comment by Ice-Cirno** [comment]
现已支持on_prefix重名命令、命令被禁用时将backdrop至启用的命令。已调整优先级：on_rex现在的优先级高于on_keyword
