### ISSUE TITLE
nonebot.scheduler 为 NoneType

### ISSUE THREAD

**Issue by yoooowi** [Ice-Cirno/HoshinoBot#180]
涉及到使用 nonebot.scheduler 的方法时就会报错
![1](https://user-images.githubusercontent.com/67884123/109427391-2783d400-7a2d-11eb-9633-6974b6084b4a.jpg)
![2](https://user-images.githubusercontent.com/67884123/109427393-29e62e00-7a2d-11eb-8210-9b37f4f4d54a.jpg)
![3](https://user-images.githubusercontent.com/67884123/109427394-2b175b00-7a2d-11eb-8651-9309c0c24196.jpg)

这是我安装了的包
![4](https://user-images.githubusercontent.com/67884123/109427402-336f9600-7a2d-11eb-8e1e-b73b3bd73451.jpg)

系统是Ubuntu 20.04 LTS

**Comment by Ice-Cirno** [comment]
```
pip3 install nonebot[scheduler]
```
