### ISSUE TITLE
Linux下拼接文件地址错误

### ISSUE THREAD

**Issue by KurenaiRyu** [Ice-Cirno/HoshinoBot#181]
我在linux下部署hoshino后发现用file协议发送文件时，转换cq代码会导致拼接错误  
eg: 
文件目录: `HoshinoBot/hoshino/modules/res/image/nr18_setu/86976473`
拼接后: `[CQ:image,file=file:////HoshinoBot/hoshino/modules/res/image/nr18_setu/86976473]`
这里多了斜杠

请问一下这个是我忽略了什么配置吗还是一个bug

**Comment by Starlento** [comment]
同样的问题，也还没解决。
他是file:///拼接一个路径，在windows上就是file:///C:/XXX，但是linux上就显得很奇怪。

**Comment by Ice-Cirno** [comment]
请使用绝对路径

**Comment by Starlento** [comment]
> 请使用绝对路径
谢谢回复。但是绝对路径下也是/home之类以/开头的地址。是否一定要是~/的地址才行呢？

**Comment by Ice-Cirno** [comment]
四个`/`没问题，在linux就是这样

**Comment by Starlento** [comment]
改成绝对路径依然是不行。而且如果文件路径不对的话，他应该FileNotFound才对。
猜猜这个图片是哪位群友头像的一部分?(30s后公布答案)[CQ:image,file=file:////root/res/img/memavatar/1041025109_cropped_memavatar.png]

**Comment by Starlento** [comment]
> 四个`/`没问题，在linux就是这样

改成绝对路径依然是不行。而且如果文件路径不对的话，他应该FileNotFound才对。
猜猜这个图片是哪位群友头像的一部分?(30s后公布答案)[CQ:image,file=file:////root/res/img/memavatar/1041025109_cropped_memavatar.png]

**Comment by Ice-Cirno** [comment]
go-cqhttp与hoshino是否在同一服务器部署？
该路径下是否有该图片？
这张图片应该是从外部下载的，是否完整、合法？
go-cqhttp是以哪个用户身份运行的？是否有root文件夹的访问权限？

**Comment by Starlento** [comment]
> go-cqhttp与hoshino是否在同一服务器部署？
> 该路径下是否有该图片？
> 这张图片应该是从外部下载的，是否完整、合法？
> go-cqhttp是以哪个用户身份运行的？是否有root文件夹的访问权限？

感谢提醒。hoshinobot和cqhttp分别是两个docker container，所以cqhttp无法直接访问到hoshinobot的资源文件。
请问大佬有没有相关的解决方法？我准备复制一份res到cqhttp同路径下面。

**Comment by KurenaiRyu** [comment]
> 感谢提醒。hoshinobot和cqhttp分别是两个docker container，所以cqhttp无法直接访问到hoshinobot的资源文件。
> 请问大佬有没有相关的解决方法？我准备复制一份res到cqhttp同路径下面。

挂个路径就好了
比如我的情况是在/root/hoshino/res/
hoshinobot容器内拿到的绝对路径是/Hoshino/res/
所以在cqhttp挂载/root/hoshino/res:/Hoshino/res/

**Comment by Ice-Cirno** [comment]
> 感谢提醒。hoshinobot和cqhttp分别是两个docker container，所以cqhttp无法直接访问到hoshinobot的资源文件。
> 请问大佬有没有相关的解决方法？我准备复制一份res到cqhttp同路径下面。

创建docker container时可以设置路径映射，将res目录映射至宿主机的同一目录。

**Comment by KurenaiRyu** [comment]
> 
> 
> 四个`/`没问题，在linux就是这样

实际上我只能够用三个`/`访问，不能够用四个。至少我现在运行的全都是自己去掉多出来一个`/`的

**Comment by KurenaiRyu** [comment]
> 
> 
> > 四个`/`没问题，在linux就是这样
> 
> 实际上我只能够用三个`/`访问，不能够用四个。至少我现在运行的全都是自己去掉多出来一个`/`的

我回去改了代码跑了一下发现没问题，估计是当时文件路径配错了
