### ISSUE TITLE
新版推特插件无法正常使用

### ISSUE THREAD

**Issue by Mercury-Lamp** [Ice-Cirno/HoshinoBot#189]
在将推特插件更新至新版本后无法正常使用，启动时报错如图所示，而之前旧版的推特插件可以正常使用。请问有解决办法吗？感谢。

环境：CentOS7，python3.8.6，go-cqhttp-v0.9.40-fix4
![报错](https://user-images.githubusercontent.com/68160576/126042286-93342527-8dec-437c-911d-5db071113301.png)

**Comment by Ice-Cirno** [comment]
从这个调用栈很难看出问题。
能否提供下`hoshino/modules/twitter/stream/__init__.py`第17行前后的代码截图 以及 nonebot版本？（使用`python3.8 -m pip freeze`查看版本）

**Comment by Mercury-Lamp** [comment]
> 从这个调用栈很难看出问题。
> 能否提供下`hoshino/modules/twitter/stream/__init__.py`第17行前后的代码截图 以及 nonebot版本？（使用`python3.8 -m pip freeze`查看版本）

感谢您的回复，原代码我并未修改过，nonebot版本为1.6.0（如下图所示）
![17行前后代码](https://user-images.githubusercontent.com/68160576/126054414-86ed992d-9459-4f28-ab45-2a6db5b123a9.png)
![nonebot版本](https://user-images.githubusercontent.com/68160576/126054417-02c5a41e-9ff1-4f0e-a4ad-c2f69f0f86b7.png)

**Comment by Ice-Cirno** [comment]
看起来似乎是bot.on_startup这个装饰器出了问题。这部分与aiocqhttp、Quart有关，请查看一下这两个库的版本。
根据https://aiocqhttp.nonebot.dev/#/changelog，aiocqhttp==1.4.0需要Quart~=0.14.0（我服务器部署的环境为aiocqhttp==1.3.0，Quart==0.11.5）

**Comment by Ice-Cirno** [comment]
经测试
> nonebot==1.6.0
> aiocqhttp==1.3.0
> Quart==0.11.5
及
> nonebot==1.8.3
> aiocqhttp==1.4.0
> Quart==0.14.1
这两种组合都是可以正常运行的

**Comment by Mercury-Lamp** [comment]
感谢您的帮助，我服务器部署的环境原为aiocqhttp==1.2.5，Quart==0.11.5。升级aiocqhttp版本后报错得到了解决，但新报了异常（如下图所示），但...似乎并不影响使用，bot还是可以正常推送推特消息（我的服务器上peony-twitter==1.1.7）
![异常](https://user-images.githubusercontent.com/68160576/126062382-95395d73-40cc-4ff0-bc13-0c08213c338b.png)

**Comment by Ice-Cirno** [comment]
这个问题是twitter那边的api有更新，会返回空字符导致peony-twitter报错，等依赖库更新吧。
我这边也出现了该问题，但不影响使用（只要能看到Got twitter event的日志即可）
