### ISSUE TITLE
关于新角色ハツネ&シオリ，是中间&符号影响吗，whois插件定位不到这个角色

### ISSUE THREAD

**Issue by 666dechaoge** [Ice-Cirno/HoshinoBot#197]
![%$L{$(IE)}_$3)(3A}3K AW](https://user-images.githubusercontent.com/49865203/132008647-4581beac-bd71-400e-8fea-61c0816e9ae5.png)
![5R N TJHCQMM`X2BTRPS~}N](https://user-images.githubusercontent.com/49865203/132008682-210f730d-a6d8-419d-86a4-b0df39b15338.png)
![O7ZM){H~RQ_B1PH(THCD$ET](https://user-images.githubusercontent.com/49865203/132008708-564e49a7-e4a4-404b-b8ad-15e90897e846.png)

**Comment by Ice-Cirno** [comment]
目测前缀树的锅，有空再修。
（应该不会有人非要输原名查吧，不会吧不会吧不会吧😅

**Comment by 666dechaoge** [comment]
![image](https://user-images.githubusercontent.com/49865203/132013401-5382b868-e974-4f2c-9b65-e57301c9918f.png)
![image](https://user-images.githubusercontent.com/49865203/132013433-122d49d1-8b17-4b82-9797-2baa97c0e2df.png)
找到了escape方法的锅。。。

**Comment by 666dechaoge** [comment]
&被转义了

**Comment by Ice-Cirno** [comment]
感谢定位，稍后我修改一下过滤方法
