### ISSUE TITLE
配置后连接反向服务器出现错误

### ISSUE THREAD

**Issue by DrMio** [Ice-Cirno/HoshinoBot#200]
大佬您好，
一切配置妥当后始终报错“开始尝试连接到反向WS universal服务器ws://127.0.0.1:8080/ws/时出现错误：No connection could be made because the target machine actively refused it”
我已经确认过Bot与go-cqhttp的端口一致，均为8080，腾讯云防火墙也开放了相应的tcp端口，但依然报错，请问是哪里出了问题呢？可以如何尝试解决呢？
因为我并不是程序员，所以如果哪里无知有打扰您着实抱歉，还请您谅解。但真的很想靠自己把这个小机器人搭起来。
感谢您百忙之中的回复~
祝好！

**Comment by clacknya** [comment]
你 127.0.0.1 本地连接与腾讯云防火墙无关，先检查 127.0.0.1 的端口能不能访问
查看监听端口情况：
``` sh
ss -anlp | grep LISTEN
```
或者
``` sh
netstat -anlp | grep LISTEN
```
也可以使用 nmap 测试
``` sh
nmap -p 8080 127.0.0.1
```

**Comment by Ice-Cirno** [comment]
运行gocqhttp之前先运行HoshinoBot，HoshinoBot会监听相应的端口（根据你配置的config/__bot__.py，默认是8080）
搭建问题可以加开发交流群问，实在搭不起来也可以加茶会群租我这边搭建好的（群号见Readme）
