### ISSUE TITLE
在将bot超级管理员更改后，无法禁言原超级管理员

### ISSUE THREAD

**Issue by davidelectricfree** [Ice-Cirno/HoshinoBot#208]
在将bot超级管理员（A账号）更改后，无法禁言原超级管理员（A账号），明明在config文件中的bot.py已经修改了别的超级管理员，仍然无法禁言a账号。当前a账号身份为普通群员，bot为群主。

**Comment by davidelectricfree** [comment]
似乎又可以了，奇怪。

**Comment by Ice-Cirno** [comment]
更改配置文件需重启生效
