### ISSUE TITLE
请问hoshino是否支持触发关键字后捕获触发者接下来一段时间内所有消息

### ISSUE THREAD

**Issue by kosakarin** [Ice-Cirno/HoshinoBot#212]
您好，请问hoshino是否支持类似于如下的场景：
触发@sv.on_fullmatch('a')后开始捕获user_id＝ev.user_id的所有群聊消息，想要实现一个上传图片的功能，如果用@sv.on_keyword('')加上一个标记来实现的话感觉log消息太多了所以想看看有没有这种实现方法，谢谢

**Comment by Ice-Cirno** [comment]
fullmatch不支持。sv.on_command支持，这是hoshino对nonebot原生on_command的包装，具体用法请参见nonebot v1.x的文档。

**Comment by kosakarin** [comment]
好的，我去看一下nonebot的相关文档，谢谢
