### ISSUE TITLE
cqhttp更新了，好像出了点问题

### ISSUE THREAD

**Issue by ID114514** [Ice-Cirno/HoshinoBot#213]
反向不到bot了，cq端一直提示：websocket: bad handshake；

**Comment by ID114514** [comment]
解决了，配置出错了，蠢到哭

**Comment by JiangSirr** [comment]
> 解决了，配置出错了，蠢到哭

我也是这个问题，是哪个地方的配置出错了？

**Comment by ID114514** [comment]
> > 解决了，配置出错了，蠢到哭
> 
> 我也是这个问题，是哪个地方的配置出错了？

反向地址。。。忘了改

**Comment by JiangSirr** [comment]
> > > 解决了，配置出错了，蠢到哭
> > 
> > 
> > 我也是这个问题，是哪个地方的配置出错了？
> 
> 反向地址。。。忘了改

cqhttp里边的地址也改了127.0.0.1:8080了，还是有问题，难不成我的是hoshinobot里边的有问题

**Comment by ID114514** [comment]
> > > > 解决了，配置出错了，蠢到哭
> > > 
> > > 
> > > 我也是这个问题，是哪个地方的配置出错了？
> > 
> > 
> > 反向地址。。。忘了改
> 
> cqhttp里边的地址也改了127.0.0.1:8080了，还是有问题，难不成我的是hoshinobot里边的有问题

hoshino是没问题的，实际上是cq地址没写好，检查一下

**Comment by li704644993** [comment]
> 

cq里面连接ws://127.0.0.1:8080/ws/ 老是connection refused ，请问是啥原因啊，能贴下你的配置文件吗

**Comment by JiangSirr** [comment]
我的cq端提示websocket: bad handshake，hoshinibot那边提示authorization header is missed。原谅没学过计算机的渣渣，只想为工会做点贡献，不知道错误在哪里。

**Comment by ID114514** [comment]
> > 
> 
> cq里面连接ws://127.0.0.1:8080/ws/老是连接拒绝吗，请问是啥原因啊，能贴下你的配置文件

这...尝试下新版cq？
