### ISSUE TITLE
启动后无法接收消息，提示msgpack not installed, MsgPackSerializer unavailable

### ISSUE THREAD

**Issue by sayri23** [Ice-Cirno/HoshinoBot#220]
log如图
![(D51HRRR@D7W@%L{T ~}13K](https://user-images.githubusercontent.com/62638560/152952818-1d87e89f-7996-421a-86c6-60b4475c75c9.png)

**Comment by sayri23** [comment]
已解决，cqhttp-mirai中没开反向websocket

**Comment by eachbol2333** [comment]
老哥，你是怎么开启的，我也是出现相同错误
