### ISSUE TITLE
关于Jinja2版本造成的ImportError

### ISSUE THREAD

**Issue by SEAFHMC** [Ice-Cirno/HoshinoBot#223]
是这样的，刚刚部署的时候一直出现</br>
`ImportError:  cannot import name  'escape' from  'jinja2'` </br>
的问题。</br>
然后我去查了下 aiocqhttp的依赖发现写的Quart>=0.14, 0.15；于是我试着更新了一下Quart版本之后成功运行了bot。怀疑是新版jinja2不支持旧版Qaurt导致的。

**Comment by DaiShengSheng** [comment]
我刚刚也遇到了这个问题，新版本的jinja2里面更改了escape的调用方式，安装jinja2的时候需要把版本限制在3.1.0以下

**Comment by CMHopeSunshine** [comment]
最近Jinja2和werkzeug的更新都导致了aiocqhttp出现调用问题，降低一下版本就行
```
pip install Jinja2==3.0.3 -U
pip install werkzeug==2.0.3 -U
```

**Comment by GirlKiller512** [comment]
我之前就有向 aiocqhttp 提交升级 Quart 版本的 issue，Quart 0.14 不支持 Python 3.10
现在 Quart 都 0.17 了那边还没升级

**Comment by jkmiku** [comment]
> 最近Jinja2和werkzeug的更新都导致了aiocqhttp出现调用问题，降低一下版本就行
> 
> ```
> pip install Jinja2==3.0.3 -U
> pip install werkzeug==2.0.3 -U
> ```

通过降版本的方式依旧无法运行，是不是需要将旧的版本卸载干净之后再安装这个。

**Comment by GirlKiller512** [comment]
> > 最近Jinja2和werkzeug的更新都导致了aiocqhttp出现调用问题，降低一下版本就行
> > ```
> > pip install Jinja2==3.0.3 -U
> > pip install werkzeug==2.0.3 -U
> > ```
> 
> 通过降版本的方式依旧无法运行，是不是需要将旧的版本卸载干净之后再安装这个。

aiocqhttp 升到 1.4.3，就可以用最新的 Quart、Jinja2 和 Werkzeug 了

**Comment by jkmiku** [comment]
> > > 最近Jinja2和werkzeug的更新都导致了aiocqhttp出现调用问题，降低一下版本就行
> > > ```
> > > pip install Jinja2==3.0.3 -U
> > > pip install werkzeug==2.0.3 -U
> > > ```
> > 
> > 
> > 通过降版本的方式依旧无法运行，是不是需要将旧的版本卸载干净之后再安装这个。
> 
> aiocqhttp 升到 1.4.3，就可以用最新的 Quart、Jinja2 和 Werkzeug 了

已经成功运行起来了，谢谢
