### ISSUE TITLE
推特转发用户不存在异常

### ISSUE THREAD

**Issue by clacknya** [Ice-Cirno/HoshinoBot#224]
默认配置文件里用户 `tsubakininiwawa` 已删号，进行轮询会造成大量 `UserNotFound` 异常

**Comment by Ice-Cirno** [comment]
https://twitter.com/tsubakinoniwa
看样子是改id了，稍后更新一下

**Comment by Ice-Cirno** [comment]
由于twitter模块对screen_name做了缓存，曾经开启过本插件的用户不会出现问题。
感谢反馈！

**Comment by clacknya** [comment]
li_hongbo 这个用户也显示不存在了

**Comment by Ice-Cirno** [comment]
> li_hongbo 这个用户也显示不存在了

已更名为 lhb3699
