### ISSUE TITLE
这个报错是什么原因呢？怎么解决

### ISSUE THREAD

**Issue by liuzj288** [Ice-Cirno/HoshinoBot#231]
![Snipaste_2022-04-16_23-55-44](https://user-images.githubusercontent.com/13833404/163682065-2afb5239-4a66-4168-80fd-480e0003b58e.png)

**Comment by Ice-Cirno** [comment]
nonebot版本问题，建议使用nonebot[scheduler]==1.8.0

**Comment by liuzj288** [comment]
emm 怎么查看现在的版本

**Comment by Ice-Cirno** [comment]
查看当前版本
```
pip list
```
安装指定版本
```
pip install nonebot[scheduler]==1.8.0
```
