### ISSUE TITLE
照readme中部署后启动时报错

### ISSUE THREAD

**Issue by PigeonMing** [Ice-Cirno/HoshinoBot#243]
PS C:\Users\Administrator\Desktop\bot\HoshinoBot> py run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import hoshino
  File "C:\Users\Administrator\Desktop\bot\HoshinoBot\hoshino\__init__.py", line 37, in <module>
    from .service import Service, sucmd
  File "C:\Users\Administrator\Desktop\bot\HoshinoBot\hoshino\service.py", line 14, in <module>
    from hoshino import log, priv, trigger
  File "C:\Users\Administrator\Desktop\bot\HoshinoBot\hoshino\priv.py", line 9, in <module>
    from hoshino import config
ImportError: cannot import name 'config' from partially initialized module 'hoshino' (most likely due to a circular import) (C:\Users\Administrator\Desktop\bot\HoshinoBot\hoshino\__init__.py)

nonebot版本是1.8.0
尝试过很多次，系统卸了一遍又一遍，确实还是解决不了

**Comment by PigeonMing** [comment]
aiocache==0.11.1
aiocqhttp==1.4.2
aiodns==3.0.0
aiofiles==0.8.0
aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.6.1
appdirs==1.4.4
APScheduler==3.9.1
async-timeout==4.0.2
asyncio==3.4.3
attrs==21.4.0
backports.zoneinfo==0.2.1
beautifulsoup4==4.9.3
blinker==1.5
cattrs==22.1.0
cchardet==2.1.7
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
cloudscraper==1.2.60
colorama==0.4.5
cycler==0.11.0
exceptiongroup==1.0.0rc8
frozenlist==1.3.1
fuzzywuzzy==0.18.0
h11==0.12.0
h2==4.1.0
hpack==4.0.0
httpcore==0.15.0
httpx==0.23.0
hypercorn==0.13.2
hyperframe==6.0.1
idna==3.3
itsdangerous==2.1.2
Jinja2==2.11.3
jmespath==1.0.1
kiwisolver==1.4.4
langid==1.1.6
lxml==4.9.1
MarkupSafe==2.0.1
matplotlib==3.2.2
msgpack==1.0.4
multidict==6.0.2
nonebot==1.8.0
numpy==1.22.4
peony-twitter==2.1.2
Pillow==9.1.1
priority==2.0.0
pycares==4.2.2
pycparser==2.21
pygtrie==2.3.3
pyparsing==3.0.9
python-dateutil==2.8.2
python-magic==0.4.27
python-magic-bin==0.4.14
pytz==2022.2.1
pytz-deprecation-shim==0.1.0.post0
Quart==0.14.1
requests==2.28.1
requests-cache==0.9.5
requests-toolbelt==0.9.1
rfc3986==1.5.0
six==1.16.0
sniffio==1.2.0
sogou-tr-free==0.0.11
soupsieve==2.3.2.post1
tinydb==4.1.1
toml==0.10.2
tzdata==2022.2
tzlocal==4.2
ujson==5.4.0
url-normalize==1.4.3
urllib3==1.26.11
Werkzeug==1.0.1
wsproto==0.15.0
yarl==1.8.1
zhconv==1.4.3
这个是安装的包

**Comment by Ice-Cirno** [comment]
> 回到资源管理器，进入hoshino文件夹，将config_example文件夹复制一份，重命名为config，然后右键使用Notepad++打开其中的__bot__.py，按照其中的注释说明进行编辑。
> > 如果您不清楚某项设置的作用，请保持默认。

这一步是否完成？

**Comment by PigeonMing** [comment]
啊啊，忘记了，抱歉，可以正常跑了！
