### ISSUE TITLE
启动后报错：cannot import name 'T_CalledAPIHook' from 'nonebot.typing'

### ISSUE THREAD

**Issue by Jacky117** [Ice-Cirno/HoshinoBot#254]
之前一直都是可以顺利运行的，但今天重启后发现了这一问题，不清楚是否是需要更新还是其他原因，以下是报错信息
![报错信息](https://user-images.githubusercontent.com/107171157/196226799-b0399879-ce19-4fc8-a17f-877ecb64f286.png)

**Comment by Ice-Cirno** [comment]
nonebot 1 与 nonebot 2 不兼容。
HoshinoBot需要使用`nonebot==1.8.0`

**Comment by Jacky117** [comment]
请问我该如何调整nonebot的版本呢？我看到nonebot的版本在安装的依赖中有提到

**Comment by Ice-Cirno** [comment]
重新执行
```
pip install -r requirements.txt
```
或手动指定版本
```
pip install nonebot==1.8.0
```

**Comment by Jacky117** [comment]
尝试过了，但还是一样的报错信息，我记得以前安装依赖的时候会在site-packages下生成一个nonebot文件的，有点搞不明白

**Comment by Ice-Cirno** [comment]
你可以使用`python3.9 -m pip list`查看当前安装的依赖包版本。
确保`nonebot`的版本是`1.8.0`而不是`2.*`

**Comment by Jacky117** [comment]
这边检查过了，确实是1.8.0版本的，但是报错依旧提示找不到nonebot这个文件
![报错信息2](https://user-images.githubusercontent.com/107171157/196238396-7d0a4968-6d35-4021-9f41-6ab7edc3ebab.png)

**Comment by Ice-Cirno** [comment]
使用`python3.9 run.py`启动呢？

**Comment by Jacky117** [comment]
原先的报错确实没了，变成了新的报错信息
![报错信息3](https://user-images.githubusercontent.com/107171157/196239274-f8491717-a5a7-44b6-b43a-93b1eb081587.png)

**Comment by clacknya** [comment]
版本太多辣，装个虚拟环境吧

**Comment by Jacky117** [comment]
最后还是选择了备份再重装了一下hoshino，现在是可以顺利运行的。辛苦咖啡佬了
