### ISSUE TITLE
【报错】部署后无法使用

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [Ice-Cirno/HoshinoBot#256]
win2012,python3.9.13
按文档win方法部署成功，以确认安装依赖，修改了config，私聊“`在？`”有回复，群内输入`help`有回复。
### 3、剩下能响应的只有帮助界面，其他指令无法响应例如`开启会战v2`，`星乃来发十连`，‘猜头像’
![image](https://user-images.githubusercontent.com/70925546/198546272-03eaf141-c72b-4ef1-b3fb-d2a6140347b3.png)

**Comment by Z735803792** [comment]
启用后端会有这种警告，请问是不是导致部分功能失效的原因？应该怎么解决？
![image](https://user-images.githubusercontent.com/70925546/198948252-50c77d9e-9b59-4e82-a2db-03f4190d3985.png)

**Comment by Z735803792** [comment]
输入服务列表，debug如下，请问是这个是什么问题，有没有解决办法
![image](https://user-images.githubusercontent.com/70925546/199175511-17109f98-a72a-40d2-8b56-c650abe4bdad.png)

**Comment by Z735803792** [comment]
已解决，通过卸载重装python后，再重装nonebot
```
pip uninstall nonebot
pip install nonebot==1.8.0
```

**Comment by lzm654** [comment]
这个在哪里运行啊

**Comment by lzm654** [comment]
我也出现了您的第一个问题，请问这个问题是如何解决的？

**Comment by Umamusume-Agnes-Digital** [comment]
> 这个在哪里运行啊

最后的回复指令，cmd运行
