### ISSUE TITLE
启动时出现类似nb2适配器的问题 

### ISSUE THREAD

**Issue by 1103859909** [Ice-Cirno/HoshinoBot#259]
![image](https://user-images.githubusercontent.com/107859647/202891065-a0ec63f9-46df-4e5c-a6e9-7ab59999a2c7.png)

**Comment by daseinem** [comment]
`ws://127.0.0.1:8080/ws/`

**Comment by Ice-Cirno** [comment]
检查你的go-cqhttp的配置

**Comment by 1103859909** [comment]
欧克  谢谢
