### ISSUE TITLE
 1013: ['七七香', '娜娜卡','nnk'','NNK', '77k', '77香'], 

### ISSUE THREAD

**Issue by yinhuise03** [Ice-Cirno/HoshinoBot#3]
https://github.com/Ice-Cirno/HoshinoBot/blob/496647e065eb16737c8219e7dc6acfc8f60ccefb/priconne/plugins/_priconne_data.py#L23

**Comment by Ice-Cirno** [comment]
nnk有歧义，折衷加上了nanaka（七七香）和neneka（似似花）
