### ISSUE TITLE
补充一波别称

### ISSUE THREAD

**Issue by yinhuise03** [Ice-Cirno/HoshinoBot#4]
https://github.com/Ice-Cirno/HoshinoBot/blob/496647e065eb16737c8219e7dc6acfc8f60ccefb/priconne/plugins/_priconne_data.py#L35

贪吃佩可：公主。贪吃佩可(夏日)：水公主。
铃莓：妹抖。 铃莓(夏日)：水妹抖。  
忍：鬼父。
美美：天兔霸断剑。
空花(大江户)：江M，江m。

**Comment by Ice-Cirno** [comment]
感谢提供！已收录
