### ISSUE TITLE
支持国服吗？

### ISSUE THREAD

**Issue by VwEl** [Ice-Cirno/HoshinoBot#58]
亲亲

**Comment by Ice-Cirno** [comment]
亲亲，Hoshino从最初开发时就支持你国唯一指定正式服代理商Sonet运营的国服呢亲！
我猜亲亲想问的是简中怀旧服的支持情况：
- 会战管理：支持3服
- jjc查询：支持按服务器实装角色过滤（暂不支持过滤星级）
- 转蛋模拟：支持mix/jp/tw/bl四种预设卡池选择（自搭可魔改，不支持自定义卡池）
- 背刺时间提醒：支持utc+9与utc+8两种时区
- 推特转发：仅日服（台服使用fb，需要fb的apikey暂时无法取得）
- 官方四格：仅支持日文原版
- rank表：人力搬运日台服（B服尚未找到靠谱、持久的内容提供源）

其他大多数功能（签到、余矿查询、常用网址、切噜语转换）本身即为通用功能
