### ISSUE TITLE
优化配置文件加载

### ISSUE THREAD

**Issue by mnixry** [Ice-Cirno/HoshinoBot#60]
可以使用yaml或者toml这类文件作为配置文件，便于修改以及后续代码无脑`git pull`
免去修改代码中修改全局变量后解决conflict的痛苦

相关issue：#61

**Comment by Ice-Cirno** [comment]
具体是哪些全局变量？

**Comment by mnixry** [comment]
py文件里面我现在需要改的就一个
github.com/Ice-Cirno/HoshinoBot/blob/hoshino/modules/pcrclanbattle/clanbattle/cmdv2.py#L322
还有公会战目录下的config.json里面的数值
好像没有太大自定义的必要？
有胜于无吧（逃）

**Comment by Ice-Cirno** [comment]
最大预约人数在下个版本将会改为各群自定义配置。
除此之外还有别的经常魔改的参数吗？

**Comment by mnixry** [comment]
> 最大预约人数在下个版本将会改为各群自定义配置。
> 除此之外还有别的经常魔改的参数吗？

我目前没有其他的需要了
