### ISSUE TITLE
New feature: Weibo poller

### ISSUE THREAD

**Issue by zzbslayer** [Ice-Cirno/HoshinoBot#62]
国服官方微博消息推送。
使用了来自 https://github.com/dataabc/weibo-crawler 的代码，并进行了一些逻辑上的调整。
目前我的 local 版本还在完善中，但是姑且能用。很多细节都需要调整。

**Comment by Ice-Cirno** [comment]
所用代码没有开源License

**Comment by zzbslayer** [comment]
如果在意License的话，自己写也未尝不可。该项目代码没多少行，主要代码量就是解析数据。其实自己写的话很有可能也写得很像。
总之，我刚刚已经给那边提了issue问一下开源协议的事情。

**Comment by zzbslayer** [comment]
关于开源协议：https://github.com/dataabc/weibo-crawler/issues/86

**Comment by Ice-Cirno** [comment]
Approved in #63 . will merge in the next version.
Thank you for your contribution!
