### ISSUE TITLE
出刀自动判断尾刀/补时刀

### ISSUE THREAD

**Issue by EdrowsLuo** [Ice-Cirno/HoshinoBot#66]
感觉没必要额外的添加这两个指令，出刀应该是可以自行判断是尾刀还是补时刀吧

**Comment by Ice-Cirno** [comment]
1. 报尾刀时程序会自动计算伤害值，比报刀+数字方便
2. 报刀时若过度虐杀，确实会自动标记尾刀
3. 只能根据伤害值来判断尾刀
4. 如果自动判断补时，需要增加一次开销较大的数据库查询，性能可能会有所降低
5. Last but not least, 分不清通常刀/尾刀/补时刀的公会不需要使用本功能
（这头像有点眼熟）

**Comment by EdrowsLuo** [comment]
基于现实情况的考虑啊，你社一会出“剩-1刀 补时1刀”了。
现在Hoshino的每分钟处理消息数很高吗？加个数据库查询只要不是慢sql那无所谓吧

**Comment by Ice-Cirno** [comment]
这种情况目测是补时刀报成通常刀了。
确实很高。
瓶颈可能不在SQL而在于python的过滤处理，具体处理可参见battlemaster.py，这部分代码基本都是一年前写的屎山，但work得很好我也不想动了。如果有更好的底层实现，欢迎pr！
我认为区分补时刀和通常刀对于大多数用户来说并不是难事。
