### ISSUE TITLE
自定义统计图表字体

### ISSUE THREAD

**Issue by mnixry** [Ice-Cirno/HoshinoBot#68]
在不修改代码的情况下可以指定统计图使用的ttf字体，也可以考虑加入资源包一键使用，主要解决在没有中文字体的系统上统计图表中文变方块的问题

**Comment by Ice-Cirno** [comment]
群中看到了你们的讨论，感觉可行。
提供下代码片段？

**Comment by mnixry** [comment]
> 群中看到了你们的讨论，感觉可行。
> 提供下代码片段？

群里好像发了代码
