### ISSUE TITLE
typo 导致无法自动推送B服官网新闻

### ISSUE THREAD

**Issue by sjj118** [Ice-Cirno/HoshinoBot#70]
研究了半天发现是[此处](https://github.com/Ice-Cirno/HoshinoBot/blob/4c9a3b95df6682165144f770ee6168d603afcb6b/hoshino/modules/priconne/news/__init__.py#L24)把`BiliSpider`写成`SonetSpider`了

```python
async def bili_news_poller():
    await news_poller(SonetSpider, svbl, 'B服官网')
```

**Comment by Ice-Cirno** [comment]
Yes, you are right. It's my fault.
This will be fixed in the next version.
