### ISSUE TITLE
酷Qair链接失效了

### ISSUE THREAD

**Issue by threer-qifu** [Ice-Cirno/HoshinoBot#73]
有没有新的链接放出啊。。

**Comment by mnixry** [comment]
这并不属于链接问题
酷Q论坛似乎为了防止爬虫做了网站来源检测，直接输入网址或者从GitHub跳转会导致无法查看网页
如果您需要下载`酷Q Air`请点击以下链接
https://dlsec.cqp.me/cqa-tuling

@Ice-Cirno 建议更新一下readme中的酷Q链接为下载直链，酷Q论坛的设置使得其很难被正常访问
