### ISSUE TITLE
抽卡问题

### ISSUE THREAD

**Issue by RicardoCZ** [Ice-Cirno/HoshinoBot#79]
抽一井的功能用不了，第一次无回复，第二次再发送就会显示今天已经抽过了

**Comment by mahosho** [comment]
重启即可再次抽取

**Comment by Ice-Cirno** [comment]
根据问题描述，最有可能的情况是第一次的回复有报错，没有成功发送。
建议检查日志报错，根据错误提示尝试解决。

**Comment by RicardoCZ** [comment]
我这边现在消息被tx截了，先挂两天再看看情况
