### ISSUE TITLE
会战数据统计web应用

### ISSUE THREAD

**Issue by Ice-Cirno** [Ice-Cirno/HoshinoBot#84]

**Comment by ArisAgeha** [comment]
https://arisageha.github.io/pcr-lanbettle-helper-build/
自己临时做了一个
大佬有什么想法吗？

**Comment by Ice-Cirno** [comment]
@ArisAgeha 嗯，大致架构差不多就是这样。之后会给bot添加api接口，前端发送请求，通过web服务器转发给bot从而获取数据。另外计划增加更多的统计图表（分数、伤害分布、出刀时间等等，完全交给前端绘制），以及导出为excel等功能。

**Comment by ArisAgeha** [comment]
请问前端部分是用哪种语言开发？如果是js 并且大佬愿意的话我想要参与开发 :)

顺便提议一下
建议为每个出刀添加一下出刀日期
因为有的人不规范使用
例如尾刀+补时刀
他们会分开2次报“出刀”
导致统计的时候某一天会多一刀
我写的demo里面的“筛选轮次（按照每3刀普通刀为一轮）”也是因此无法正常运作
为每一刀标记上日期（或者标记上第n天）可以解决这个问题

**Comment by Ice-Cirno** [comment]
@ArisAgeha 大概会开一个新的repo，用vue.js之类的框架来写，绘图可以用chart.js，大致就是一个简单的单页面应用，认证q号与群号的关联后，从数据库拿明细，绘图完全交给前端。语言嘛...当然是html+css+js/ts（前端我也不是很懂，知道的框架就这些，如果有更好的实现方法可以提）
关于提议：
- 出刀时间后台有记录，可以拿到
- 出刀命令重做后会严格一些，自动判定补时刀，收尾后只能报补时刀（说白了就是照抄yobot的逻辑）
- clanbattle v3会以出刀队列为核心（现在是以出刀记录为核心），每个公会有5个队列，队列中的成员有(预约|进本|暂停|挂树)等状态，增加筛刀/白嫖刀计算等feature。

**Comment by ArisAgeha** [comment]
> @ArisAgeha 大概会开一个新的repo，用vue.js之类的框架来写，绘图可以用chart.js，大致就是一个简单的单页面应用，认证q号与群号的关联后，从数据库拿明细，绘图完全交给前端。语言嘛...当然是html+css+js/ts（前端我也不是很懂，知道的框架就这些，如果有更好的实现方法可以提）
> 关于提议：
> 
> * 出刀时间后台有记录，可以拿到
> * 出刀命令重做后会严格一些，自动判定补时刀，收尾后只能报补时刀（说白了就是照抄yobot的逻辑）
> * clanbattle v3会以出刀队列为核心（现在是以出刀记录为核心），每个公会有5个队列，队列中的成员有(预约|进本|暂停|挂树)等状态，增加筛刀/白嫖刀计算等feature。

话说yobot没用过2333
其实我就是公会里在用这个bot 
然后觉得统计不实用就自己写了一份

技术栈基本没问题
图表只用过echart 不过反正看看文档就ok了
大概什么时候动工呢？
需要帮忙参与开发吗？

**Comment by ArisAgeha** [comment]
> @ArisAgeha web端的开发会放得靠后些，首先要重构Service和重写clanbattle v3，预计7月中旬弄个测试版出来。demo先把明细做出来（和你写的pcr-lanbettle-helper-build差不多），绘图的功能就比较零碎、便于分工了，首先复刻已有的伤害和分数统计，然后再加出刀时间、出刀数目等等。echart也可以，绘图的实现多种多样，怎么方便怎么来。
> 
> 但需要解决一个技术难点：权限认证。需要用QQ号+密码登录，然后查询该QQ所关联的公会，确认权限后才可看到数据。密码在数据库的存储方式需要一段时间研究。
> 
> 开发时倒是可以先不管权限的问题，等api开发出来，前端就可以开工了。

其实我一开始也打算做上图表的
不过因为我只能查看到 “!查看出刀”的数据
实在没什么数据好做的...加上昨晚好困就放弃了（其实那个DEMO总共就只写了3个小时）

权限认证的话 如果想要快速开发 就用JWT好了 注册甚至都不用认证QQ或者邮箱
密码加密储存的话用什么jscrypt、bcrypt、**crypt都可以

如果是比较闲、想做得安全一点的话，就最好加个第三方登录或者邮箱验证码注册吧
但是我个人不太推荐，搞这么多一套的话，用户用起来不方便
（特别是公会成员，有相当一部分都是被会长逼着在QQ里出刀的，你现在还让他们去注册、验证...）
那还不如直接做个脱离HoshinoBot的独立系统了
web端要怎么让用户安全使用的同时节省用户的操作量也要考量一下

**Comment by yuudi** [comment]
> 
> 权限认证的话 如果想要快速开发 就用JWT好了 注册甚至都不用认证QQ或者邮箱
> 密码加密储存的话用什么jscrypt、bcrypt、**crypt都可以
> 
> 如果是比较闲、想做得安全一点的话，就最好加个第三方登录或者邮箱验证码注册吧
> 但是我个人不太推荐，搞这么多一套的话，用户用起来不方便
> （特别是公会成员，有相当一部分都是被会长逼着在QQ里出刀的，你现在还让他们去注册、验证...）
> 那还不如直接做个脱离HoshinoBot的独立系统了

权限认证可以直接让成员直接在 bot 端一键完成注册。最好也保留 web 端注册，这样的话没有 QQ 的人也能用。


> web端要怎么让用户安全使用的同时节省用户的操作量也要考量一下

我认为 web 端主要目的是为了展示复杂数据和进行复杂操作，简单的报刀操作直接在 bot 端完成即可，web 端主要是展示图表和进行批量改刀删刀。

**Comment by ArisAgeha** [comment]
确实 不过“没有QQ的人也能用”这个似乎没有什么意义吧？web端的统计信息是基于QQ群的会战记录来生成的，脱离了QQ有什么意义呢？

**Comment by yuudi** [comment]
> 
> 
> 确实 不过“没有QQ的人也能用”这个似乎没有什么意义吧？web端的统计信息是基于QQ群的会战记录来生成的，脱离了QQ有什么意义呢？

因为有不愿意用QQ的人，也有公会战记录和分析需求的。

目前有纯 web 版的公会战记录器，还有微信小程序版的。我觉得不如直接放在一起比较方便。

统计信息既可以从 QQ 消息中收集，也可以从 web 端录入。

~~提需求的人站着说话不腰疼（~~

**Comment by Auirwind** [comment]
可以说十分感兴趣了。
目前市面上常用的hoshinobot和yobot
在多功能上 hoshinobot全面领先
唯独没有WEB界面让很多人感觉麻烦，其实也只是动手敲几个码的事情
能加入WEB后台的话，基本可能很多群要告别yobot了

**Comment by Milkitic** [comment]
基于yobot的api制作了一个自定义图表、表格工具，可以整合至 `/yobot/clan/xxx/statistics/` 页面嘛？
虽然是客户端程序，无法给页面，只能给下载页面链接
亦或是有没有考虑增加一个基于本应用api衍生出的应用列表整合
十分蟹蟹

**Comment by Cathgao** [comment]
用过yobot，很喜欢他的会战统计功能。要是能把yobot整合进hoshinobot或者有方法共存就好了

**Comment by Cathgao** [comment]
> 用过yobot，很喜欢他的会战统计功能。要是能把yobot整合进hoshinobot或者有方法共存就好了

还有能否增加PCR日程推送？或者已经有此功能我没找到？

**Comment by laipz8200** [comment]
> 用过yobot，很喜欢他的会战统计功能。要是能把yobot整合进hoshinobot或者有方法共存就好了

共存是可以的，按以下方式组织你的`hoshino`目录结构:

```
.
├── aiorequests.py
├── config
├── __init__.py
├── log.py
├── modules
│   ├── botmanage
│   ├── deepchat
│   ├── dice
│   ├── groupmaster
│   ├── hourcall
│   ├── kancolle
│   ├── mikan
│   ├── pcrclanbattle
│   ├── priconne
│   ├── setu
│   ├── translate
│   ├── twitter
│   └── yobot
│       └── yobot
│           ├── docker-compose.yml
│           ├── Dockerfile
│           ├── docs
│           ├── __init__.py
│           ├── LICENSE
│           ├── __pycache__
│           ├── README.md
│           ├── scripts
│           └── src
├── msghandler.py
├── priv.py
├── R.py
├── service.py
├── tree.txt
├── trigger.py
├── typing.py
└── util
```

然后修改你的`HoshinoBot/hoshino/config/__bot__.py`文件:

```python
MODULES_ON = {
    ......
    ......
    'yobot'
}
```

重启即可

**Comment by Cathgao** [comment]
> > 用过yobot，很喜欢他的会战统计功能。要是能把yobot整合进hoshinobot或者有方法共存就好了
> 
> 共存是可以的，按以下方式组织你的`hoshino`目录结构:
> 
> ```
> .
> ├── aiorequests.py
> ├── config
> ├── __init__.py
> ├── log.py
> ├── modules
> │   ├── botmanage
> │   ├── deepchat
> │   ├── dice
> │   ├── groupmaster
> │   ├── hourcall
> │   ├── kancolle
> │   ├── mikan
> │   ├── pcrclanbattle
> │   ├── priconne
> │   ├── setu
> │   ├── translate
> │   ├── twitter
> │   └── yobot
> │       └── yobot
> │           ├── docker-compose.yml
> │           ├── Dockerfile
> │           ├── docs
> │           ├── __init__.py
> │           ├── LICENSE
> │           ├── README.md
> │           ├── scripts
> │           └── src
> ├── msghandler.py
> ├── priv.py
> ├── R.py
> ├── service.py
> ├── trigger.py
> ├── typing.py
> └── util
> ```
> 
> 然后修改你的`HoshinoBot/hoshino/config/__bot__.py`文件:
> 
> ```python
> MODULES_ON = {
>     ......
>     ......
>     'yobot'
> }
> ```
> 
> 重启即可

好的我试试，感谢解答

**Comment by Ice-Cirno** [comment]
https://hoshinobot.cc (for clanbattlev4)
