### ISSUE TITLE
Service层重做

### ISSUE THREAD

**Issue by Ice-Cirno** [Ice-Cirno/HoshinoBot#87]
当前Service层存在诸多问题（重要性排序）：
- 命令解析常以空格作为分隔符，与用户直觉不符
- 权限判定及触发条件判断会被执行多次，运行效率低
- 新增的触发条件`on_rex`、`on_keyword`不支持NICKNAME判定
- 帮助文档为集中式，过长易刷屏
- Service名为英文，对用户不友好
- *不支持私聊*：设计如此，Service的目的就是实现分群的启/禁用和权限控制，个别命令可能需要私聊支持，应采用别的实现方式。

重做方案（优先度排序）：
- [x] 新增`on_prefix`触发条件，利用前缀触发，无需空格
- [x] 新增`on_fullmatch`触发条件，实现上属于`on_prefix`的子集
- [x] 使用`on_prefix`替代带参的`on_command`，使用`on_fullmatch`替代无参的`on_command`
- [x] 保留`on_keyword`和`on_rex`但不建议使用（运行效率低）
- [x] 使用统一的入口函数，1条消息在Service层仅需1次判定，使用trie实现最长前缀匹配，仅触发一个function
- [x] 保持原生`on_command`的兼容性
- [x] Service自带说明文档，由集中式改为分布式

以下内容暂时先不做了，有需要再新开issue：
- 入口函数内处理NICKNAME，NICKNAME改为分Q号设置
- 删除`on_natrual_language`的支持：基本无需使用
- 添加Service别名，可用中文

**Comment by Hieuzest** [comment]
希望能支持Service管理和reload热更新
（实现上，反正要做统一入口了的话，可以直接cqhttp的subscribe）

（其实我原本是希望service能merge进nonoebot然后让Plugin=Set[Service]的。。）
~~（等我有空了踢掉nonebot自己搓一套）~~

**Comment by Ice-Cirno** [comment]
@Hieuzest 
- 不清楚你的“Service管理”是指什么？
- reload热更新感觉会有很多坑，有不少功能内部是有状态的，我对python reload module这块也不太熟悉，个人觉得bot也无热更新需要（毕竟重启一下也就几秒钟）。
- 我不建议代码热更新，而应该是配置热更新，如卡池、会战boss血量等易变数据，应写入config.json文件，修改配置文件即可实现热更新。
- 重做后确实和nonebot没啥关系了，理论上可以抛去nonebot的依赖而仅依赖aiocqhttp（但要把nonebot的插件加载、at_me检查等部分的代码给抄过来）
- Service已经实现了分群的启/禁用，也就无需使用nonebot最近新添加的PluginManage来控制了，我粗略地看过文档，PluginManage也是只能控制全局启/禁用，而无法将细粒度做到群。

nonebot那套逻辑主要是基于session的，而Hoshino的大多数指令都是一次性的，并不需要所谓的“会话”特性。个人觉得，nonebot主要是为了解决“交互”，而hoshino.service主要是为了解决"分群权限管理"。这一套Service撸下来确实和自己撸一套框架差不多了.....但是否能merge进nonebot呢？我觉得还是不太能的，因为两者的设计理念差别较大。

**Comment by yuudi** [comment]
`on_prefix` 已经在 [nonebot#195](https://github.com/nonebot/nonebot/pull/195) 中实现了
