### ISSUE TITLE
config重做

### ISSUE THREAD

**Issue by Ice-Cirno** [Ice-Cirno/HoshinoBot#88]
现在的`config.json`文件散落于各个模块中，不便管理和修改。
重做后将集中到一个folder内，改用py配置，好处是可以利用上编辑器的智能提示，也可用上封装好的class

**Comment by yuudi** [comment]
如果用 py 配置的话，打包成 exe 时会有一点点麻烦。

**Comment by Ice-Cirno** [comment]
基本完成，剩下的kancolle/query/fleet clanbattle/battlemaster gacha/gacha因为计划总体重写，暂时不管了。
