### ISSUE TITLE
clanbattle-cmdv3

### ISSUE THREAD

**Issue by Ice-Cirno** [Ice-Cirno/HoshinoBot#89]
- 采用前缀触发、关键词触发
- 新增进本队列概念
- 新增出刀暂停、白嫖刀所需伤害计算等功能

**Comment by zzpong** [comment]
以下两点与代码理念相关，因此未轻易修改，仅作建议：
- 成员“退会”后其对应“出刀记录”的处理方式：目前实现方式为成员与出刀管理相互独立，但会导致移除某些成员后，其对应出刀数据无法查询（只可虚空删除记录），公会战进度无法正确归零的情况。该情况一般不会发生，但仍可视为潜在问题考虑。
- 批量删刀(eid>?)及根据用户uid删刀：容易实现，但误删代价过大，且错误报刀的频率要远比正常报刀低。

**Comment by Ice-Cirno** [comment]
@zzpong 出刀记录即使退会后也应保留，因为现在的实现方式中公会的进度是无记录的，完全根据出刀记录来计算；经测试，v2版本即便退会也可显示出刀记录（但不显示名字只显示QQ号了），出刀记录命令只显示当天，还请多多留意。
“批量删刀(eid>?)及根据用户uid”这两种方式我认为无必要，现在唯一需要的情景是：测试功能后需要重置，那么只需增加一个重置的命令即可。批量删刀操作比较危险，应进行2次确认。

在v3的实现计划中，公会的进度将显式地记录下来，不再根据出刀记录来计算，方便调整进度。
重置命令也在计划中。

**Comment by zzpong** [comment]
@Ice-Cirno 
感谢回复~
- “出刀记录仅显示当天”的问题是我测试的疏忽，在此表示抱歉。我遇到上面提到问题的情况是“本月会战未开，某会员被踢出，而该会员在本月被踢出前胡乱填了几刀。查询会战进度发现在二王，出刀记录为空（因为仅显示当天）”。
- 批量删刀的确比较危险，需要二次确认。一般使用时很少遇到批量删刀，主要需求在功能测试。如果在重置功能之外还有其他更为多样的功能，个人觉的会更方便些。
- 目前在“出刀记录”里，“补时刀”、“尾刀”间是没有联系的，如果删除“尾刀”，其对应的“补时刀”并不会消失。当然，这个并不是“程序需要”，而是“程序更人性化”所需求的。如果想要增加这些刀之间的联系、又或是成员与出刀之间的联系（可用于移除本月退会，但又在本月会战开始前胡乱写的出刀记录），我觉得可能大版本更新是最好的时机。

关于v3的实现计划：
- 新的公会进度算法是不是表示出刀与进度间独立了呢？如果是的话，错误报刀的删刀就无法及时更新到公会进度了吧？
- 重置命令时希望不要把老命令完全傻瓜化，真的只能报“出刀”了。我觉得如果傻瓜指令与一般指令同时走着会很不错。
- 我觉得可用于移除本月退会，但又在本月会战开始前胡乱写的出刀记录。不过实现优先度极低，可以先考虑别的。

**Comment by Ice-Cirno** [comment]
done.
