### ISSUE TITLE
every can report damage 3 times !

### ISSUE THREAD

**Issue by pekoprincess** [Ice-Cirno/HoshinoBot#94]

**Comment by pekoprincess** [comment]
version: yobot[v3.6.2_beta_2]便携版

**Comment by pekoprincess** [comment]
I can only report damage 3 times in one day. include when I report damage instead of others!

**Comment by pekoprincess** [comment]
chinese:每个人只能每天上报三次伤害，代替报刀则消耗次数，希望修正统计方式。

**Comment by Ice-Cirno** [comment]
@pekoprincess 你走错门了，这里是HoshinoBot。本bot的会战管理并未做出刀总数的限制。
